apiVersion: v1
kind: Pod
metadata:
  name: spark-nginx
  namespace: spark
  labels:
    app: spark-nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      - name: index-html
        mountPath: /usr/share/nginx/html/index.html
        subPath: index.html
  volumes:
    - name: nginx-conf
      configMap:
        name: spark-nginx-config
    - name: index-html
      configMap:
        name: spark-nginx-index
