apiVersion: v1
kind: Pod
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  containers:
  - name: spark-node
    image: "graminedirect.azurecr.io/spark-spool-direct:latest"
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "3.5"
        memory: "11Gi"
      limits:
        cpu: "3.5"
        memory: "11Gi"
